### ISSUE TITLE
I encountered an error message

### ISSUE THREAD

**Issue by trappedinspacetime** [C-Loftus/Watercolor#2]
Ubuntu 22.04 Mate Desktop.

I need this accessibility feature because I have a neuromuscular disease. 
So I congratulate you on your assisstive project.

          make run
          /usr/bin/python3 .atspi-server/main.py
          TALON SERVER SERVING ON /tmp/watercolor-at-spi-server.sock
          Traceback (most recent call last):
            File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/create_coords.py", line 153, in dump
              old_app, old_root = Desktop.getRoot()
            File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/create_coords.py", line 47, in getRoot
              states = get_states(window)
            File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/lib.py", line 42, in get_states
              for state in list(accessible_obj.get_state_set().get_states()):
          AttributeError: 'NoneType' object has no attribute 'get_state_set'
          Traceback (most recent call last):
            File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/create_coords.py", line 153, in dump
              old_app, old_root = Desktop.getRoot()
            File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/create_coords.py", line 47, in getRoot
              states = get_states(window)
            File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/lib.py", line 42, in get_states
              for state in list(accessible_obj.get_state_set().get_states()):
          AttributeError: 'NoneType' object has no attribute 'get_state_set'

**Comment by C-Loftus** [comment]
Thanks for filing this.

I pushed some code to handle this. Please run `git pull` and then see if it helps.

I am a bit puzzled how this could have even occurred, since Atspi tells us there are `X` children for the active app, but in your example, one of those `X` children are null. If things are still not working, make sure atspi is running and let me know what app you expected to be focused at the time in which you were launching watercolor.

```shell
ps aux | grep 'at-spi'
```

**Comment by trappedinspacetime** [comment]
@C-Loftus Thank you for responding. 
I tried it with `Firefox` browser. 
It didn't print any error message till I launch `Firefox`.
`at-spi` is working.
I use Compiz as a desktop manager. 

        make run
        /usr/bin/python3 .atspi-server/main.py
        TALON SERVER SERVING ON /tmp/watercolor-at-spi-server.sock
        Traceback (most recent call last):
          File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/create_coords.py", line 236, in dump
            A11yTree.constructor_handle.join()
        AttributeError: 'NoneType' object has no attribute 'join'
        Traceback (most recent call last):
          File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/create_coords.py", line 236, in dump
            A11yTree.constructor_handle.join()
        AttributeError: 'NoneType' object has no attribute 'join'
        Traceback (most recent call last):
          File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/create_coords.py", line 236, in dump
            A11yTree.constructor_handle.join()
        AttributeError: 'NoneType' object has no attribute 'join'
        Traceback (most recent call last):
          File "/home/kenn/Desktop/2024-06/Watercolor/.atspi-server/create_coords.py", line 236, in dump
            A11yTree.constructor_handle.join()
        AttributeError: 'NoneType' object has no attribute 'join'

**Comment by C-Loftus** [comment]
Thanks for the debug message.

I pushed another update for you. But I am still puzzled since the case this is running into should never occur. From what I can see, it seems like Firefox is not dumping any elements. I have not used Mate or Compiz so I am unsure if this is a quirk of them in some way. (For context, that error signified a thread handle was null, but that was right after it was created. So it seems like the thread immediately finished) 

Please note that with Firefox specifically [you need to launch it **after** atspi is initialized](https://github.com/C-Loftus/Watercolor/blob/main/docs/app-wiki.md) in order to get atspi working. (This is out of my control, and just the way that Firefox works). Although I am not sure if this would be giving the error we are seeing.  

I think we may need extra info to debug this. Can you send me the `atspi_log.txt` log file that is output in the same directory as Watercolor after running `make run`?
